/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ITokenReplacement,
  ITokenReplacementInterface,
} from "../../contracts/ITokenReplacement";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "oldToken",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newToken",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "TokenReplaced",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "oldToken",
        type: "address",
      },
      {
        internalType: "address",
        name: "newToken",
        type: "address",
      },
    ],
    name: "migrateBalances",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ITokenReplacement__factory {
  static readonly abi = _abi;
  static createInterface(): ITokenReplacementInterface {
    return new Interface(_abi) as ITokenReplacementInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ITokenReplacement {
    return new Contract(address, _abi, runner) as unknown as ITokenReplacement;
  }
}
