/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace CapTable {
  export type CorporateActionStruct = {
    id: BigNumberish;
    actionType: string;
    blockNumber: BigNumberish;
    timestamp: BigNumberish;
    data: BytesLike;
  };

  export type CorporateActionStructOutput = [
    id: bigint,
    actionType: string,
    blockNumber: bigint,
    timestamp: bigint,
    data: string
  ] & {
    id: bigint;
    actionType: string;
    blockNumber: bigint;
    timestamp: bigint;
    data: string;
  };
}

export interface CapTableInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "corporateActionById"
      | "corporateActionCount"
      | "createdAt"
      | "getCompanyInfo"
      | "getCorporateAction"
      | "getCorporateActionCount"
      | "isTokenLinked"
      | "linkToken"
      | "name"
      | "nextActionId"
      | "owner"
      | "recordCorporateAction"
      | "renounceOwnership"
      | "symbol"
      | "token"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CapTableCreated"
      | "CorporateActionRecorded"
      | "OwnershipTransferred"
      | "TokenLinked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "corporateActionById",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "corporateActionCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "createdAt", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getCompanyInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCorporateAction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCorporateActionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isTokenLinked",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "linkToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "nextActionId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordCorporateAction",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "corporateActionById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "corporateActionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createdAt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCompanyInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCorporateAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCorporateActionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTokenLinked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "linkToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextActionId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordCorporateAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace CapTableCreatedEvent {
  export type InputTuple = [
    capTable: AddressLike,
    name: string,
    symbol: string,
    issuer: AddressLike
  ];
  export type OutputTuple = [
    capTable: string,
    name: string,
    symbol: string,
    issuer: string
  ];
  export interface OutputObject {
    capTable: string;
    name: string;
    symbol: string;
    issuer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CorporateActionRecordedEvent {
  export type InputTuple = [
    actionId: BigNumberish,
    actionType: string,
    blockNumber: BigNumberish
  ];
  export type OutputTuple = [
    actionId: bigint,
    actionType: string,
    blockNumber: bigint
  ];
  export interface OutputObject {
    actionId: bigint;
    actionType: string;
    blockNumber: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenLinkedEvent {
  export type InputTuple = [capTable: AddressLike, token: AddressLike];
  export type OutputTuple = [capTable: string, token: string];
  export interface OutputObject {
    capTable: string;
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CapTable extends BaseContract {
  connect(runner?: ContractRunner | null): CapTable;
  waitForDeployment(): Promise<this>;

  interface: CapTableInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  corporateActionById: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, string] & {
        id: bigint;
        actionType: string;
        blockNumber: bigint;
        timestamp: bigint;
        data: string;
      }
    ],
    "view"
  >;

  corporateActionCount: TypedContractMethod<[], [bigint], "view">;

  createdAt: TypedContractMethod<[], [bigint], "view">;

  getCompanyInfo: TypedContractMethod<
    [],
    [[string, string, string, string, bigint]],
    "view"
  >;

  getCorporateAction: TypedContractMethod<
    [id: BigNumberish],
    [CapTable.CorporateActionStructOutput],
    "view"
  >;

  getCorporateActionCount: TypedContractMethod<[], [bigint], "view">;

  isTokenLinked: TypedContractMethod<[], [boolean], "view">;

  linkToken: TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;

  name: TypedContractMethod<[], [string], "view">;

  nextActionId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  recordCorporateAction: TypedContractMethod<
    [_actionType: string, _data: BytesLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  symbol: TypedContractMethod<[], [string], "view">;

  token: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "corporateActionById"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, string] & {
        id: bigint;
        actionType: string;
        blockNumber: bigint;
        timestamp: bigint;
        data: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "corporateActionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createdAt"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCompanyInfo"
  ): TypedContractMethod<
    [],
    [[string, string, string, string, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCorporateAction"
  ): TypedContractMethod<
    [id: BigNumberish],
    [CapTable.CorporateActionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCorporateActionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isTokenLinked"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "linkToken"
  ): TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "nextActionId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordCorporateAction"
  ): TypedContractMethod<
    [_actionType: string, _data: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "CapTableCreated"
  ): TypedContractEvent<
    CapTableCreatedEvent.InputTuple,
    CapTableCreatedEvent.OutputTuple,
    CapTableCreatedEvent.OutputObject
  >;
  getEvent(
    key: "CorporateActionRecorded"
  ): TypedContractEvent<
    CorporateActionRecordedEvent.InputTuple,
    CorporateActionRecordedEvent.OutputTuple,
    CorporateActionRecordedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TokenLinked"
  ): TypedContractEvent<
    TokenLinkedEvent.InputTuple,
    TokenLinkedEvent.OutputTuple,
    TokenLinkedEvent.OutputObject
  >;

  filters: {
    "CapTableCreated(address,string,string,address)": TypedContractEvent<
      CapTableCreatedEvent.InputTuple,
      CapTableCreatedEvent.OutputTuple,
      CapTableCreatedEvent.OutputObject
    >;
    CapTableCreated: TypedContractEvent<
      CapTableCreatedEvent.InputTuple,
      CapTableCreatedEvent.OutputTuple,
      CapTableCreatedEvent.OutputObject
    >;

    "CorporateActionRecorded(uint256,string,uint256)": TypedContractEvent<
      CorporateActionRecordedEvent.InputTuple,
      CorporateActionRecordedEvent.OutputTuple,
      CorporateActionRecordedEvent.OutputObject
    >;
    CorporateActionRecorded: TypedContractEvent<
      CorporateActionRecordedEvent.InputTuple,
      CorporateActionRecordedEvent.OutputTuple,
      CorporateActionRecordedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TokenLinked(address,address)": TypedContractEvent<
      TokenLinkedEvent.InputTuple,
      TokenLinkedEvent.OutputTuple,
      TokenLinkedEvent.OutputObject
    >;
    TokenLinked: TypedContractEvent<
      TokenLinkedEvent.InputTuple,
      TokenLinkedEvent.OutputTuple,
      TokenLinkedEvent.OutputObject
    >;
  };
}
