/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iRolesSol from "./IRoles.sol";
export type { iRolesSol };
export type { CapTable } from "./CapTable";
export type { ChainEquityToken } from "./ChainEquityToken";
export type { ITokenReplacement } from "./ITokenReplacement";
