/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ITokenReplacementInterface extends Interface {
  getFunction(nameOrSignature: "migrateBalances"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "TokenReplaced"): EventFragment;

  encodeFunctionData(
    functionFragment: "migrateBalances",
    values: [AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "migrateBalances",
    data: BytesLike
  ): Result;
}

export namespace TokenReplacedEvent {
  export type InputTuple = [
    oldToken: AddressLike,
    newToken: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    oldToken: string,
    newToken: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    oldToken: string;
    newToken: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ITokenReplacement extends BaseContract {
  connect(runner?: ContractRunner | null): ITokenReplacement;
  waitForDeployment(): Promise<this>;

  interface: ITokenReplacementInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  migrateBalances: TypedContractMethod<
    [oldToken: AddressLike, newToken: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "migrateBalances"
  ): TypedContractMethod<
    [oldToken: AddressLike, newToken: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "TokenReplaced"
  ): TypedContractEvent<
    TokenReplacedEvent.InputTuple,
    TokenReplacedEvent.OutputTuple,
    TokenReplacedEvent.OutputObject
  >;

  filters: {
    "TokenReplaced(address,address,uint256)": TypedContractEvent<
      TokenReplacedEvent.InputTuple,
      TokenReplacedEvent.OutputTuple,
      TokenReplacedEvent.OutputObject
    >;
    TokenReplaced: TypedContractEvent<
      TokenReplacedEvent.InputTuple,
      TokenReplacedEvent.OutputTuple,
      TokenReplacedEvent.OutputObject
    >;
  };
}
