/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  Roles,
  RolesInterface,
} from "../../../contracts/IRoles.sol/Roles";

const _abi = [
  {
    inputs: [],
    name: "ROLE_ADMIN",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ROLE_INVESTOR",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ROLE_ISSUER",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x610180610053600b82828239805160001a607314610046577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361061004b5760003560e01c80635645927a14610050578063794d38501461006e578063d391014b1461008c575b600080fd5b6100586100aa565b604051610065919061012f565b60405180910390f35b6100766100ce565b604051610083919061012f565b60405180910390f35b6100946100f2565b6040516100a1919061012f565b60405180910390f35b7faf6434f6eb154f0a8fb99159f5a5d62e65539f790f541f86c973b2514c8e39b281565b7fb5f4ba1c5fe0704bb1c4399e6baa562444b507b8daf8d7c95ffa2d49b06b442c81565b7f2172861495e7b85edac73e3cd5fbb42dd675baadf627720e687bcfdaca02509681565b6000819050919050565b61012981610116565b82525050565b60006020820190506101446000830184610120565b9291505056fea26469706673582212205b6c5a242a93aa80e7fb73d6f6867de4ab415bbb108e98886e7555dabf75760d64736f6c63430008180033";

type RolesConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: RolesConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Roles__factory extends ContractFactory {
  constructor(...args: RolesConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Roles & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Roles__factory {
    return super.connect(runner) as Roles__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): RolesInterface {
    return new Interface(_abi) as RolesInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Roles {
    return new Contract(address, _abi, runner) as unknown as Roles;
  }
}
