/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  Roles,
  RolesInterface,
} from "../../../contracts/IRoles.sol/Roles";

const _abi = [
  {
    inputs: [],
    name: "ROLE_ADMIN",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ROLE_INVESTOR",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ROLE_ISSUER",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x61010661003a600b82828239805160001a60731461002d57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060475760003560e01c80635645927a14604c578063794d3850146084578063d391014b1460aa575b600080fd5b60727faf6434f6eb154f0a8fb99159f5a5d62e65539f790f541f86c973b2514c8e39b281565b60405190815260200160405180910390f35b60727fb5f4ba1c5fe0704bb1c4399e6baa562444b507b8daf8d7c95ffa2d49b06b442c81565b60727f2172861495e7b85edac73e3cd5fbb42dd675baadf627720e687bcfdaca0250968156fea2646970667358221220142196884312110ecb1bfb8d1b8fd1acfdf916dabcc3eaef010dd7453cb95e3e64736f6c63430008180033";

type RolesConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: RolesConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Roles__factory extends ContractFactory {
  constructor(...args: RolesConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Roles & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Roles__factory {
    return super.connect(runner) as Roles__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): RolesInterface {
    return new Interface(_abi) as RolesInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Roles {
    return new Contract(address, _abi, runner) as unknown as Roles;
  }
}
